# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: daniel@schiavini.nl
author_name: Daniel Schiavini
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: server
labextension_name: titanoboa-jupyterlab-extension
mimetype: ''
mimetype_name: ''
project_short_description:
  A JupyterLab extension for integrating with the Vyper programming
  language by using Titanoboa.
python_name: titanoboa_jupyterlab
repository: https://github.com/DanielSchiavini/titanoboa-jupyterlab
test: true
viewer_name: ''
